### ISSUE TITLE
asus-wmi-sensors-9999 fails to src_install with 'No such file or directory: b'.ko'

### ISSUE THREAD

**Issue by stefson** [gyakovlev/geo-overlay#1]
hey there, I found your ebuilds by accident and wanted to try them, but the live ebuild doesn't fully work: 

```
 * Preparing  module
make -j12 HOSTCC=x86_64-pc-linux-gnu-gcc CROSS_COMPILE=x86_64-pc-linux-gnu- 'LDFLAGS=-m elf_x86_64' TARGET=4.14.129-ryzen KERNEL_BUILD=/usr/src/linux KBUILD_VERBOSE=1 modules 
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
mkdir -p /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/.tmp_versions ; rm -f /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999
(cat /dev/null;   echo kernel//var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/asus-wmi-sensors.ko;) > /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/modules.order
  x86_64-pc-linux-gnu-gcc -Wp,-MD,/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/.asus-wmi-sensors.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=znver1 -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -Wno-attribute-alias -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fomit-frame-pointer -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -DASUS_WMI_SENSORS_DRIVER_VERSION='"1ed9fc6"'  -DMODULE  -DKBUILD_BASENAME='"asus_wmi_sensors"'  -DKBUILD_MODNAME='"asus_wmi_sensors"' -c -o /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/.tmp_asus-wmi-sensors.o /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/asus-wmi-sensors.c
   ./tools/objtool/objtool orc generate  --module --no-fp  --retpoline "/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/.tmp_asus-wmi-sensors.o";
make -f ./scripts/Makefile.modpost
  find /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/.tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | scripts/mod/modpost -m  -i ./Module.symvers -I /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/Module.symvers  -o /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/Module.symvers -S  -w  -s -T -
  x86_64-pc-linux-gnu-gcc -Wp,-MD,/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/.asus-wmi-sensors.mod.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=znver1 -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -Wno-attribute-alias -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fomit-frame-pointer -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -DASUS_WMI_SENSORS_DRIVER_VERSION='"1ed9fc6"'  -DKBUILD_BASENAME='"asus_wmi_sensors.mod"'  -DKBUILD_MODNAME='"asus_wmi_sensors"' -DMODULE  -c -o /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/asus-wmi-sensors.mod.o /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/asus-wmi-sensors.mod.c
  x86_64-pc-linux-gnu-ld -r -m elf_x86_64 -T ./scripts/module-common.lds --build-id  -o /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/asus-wmi-sensors.ko /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/asus-wmi-sensors.o /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999/asus-wmi-sensors.mod.o ;  true
>>> Source compiled.
>>> Test phase [not enabled]: sys-kernel/asus-wmi-sensors-9999

>>> Install asus-wmi-sensors-9999 into /var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/image/ category sys-kernel
 * Installing  module
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'.ko'
 * ERROR: sys-kernel/asus-wmi-sensors-9999::gentoo-extras failed (install phase):
 *   doins failed
 * 
 * If you need support, post the output of `emerge --info '=sys-kernel/asus-wmi-sensors-9999::gentoo-extras'`,
 * the complete build log and the output of `emerge -pqv '=sys-kernel/asus-wmi-sensors-9999::gentoo-extras'`.
 * The complete build log is located at '/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999'
 * S: '/var/tmp/portage/sys-kernel/asus-wmi-sensors-9999/work/asus-wmi-sensors-9999'
```

(the non live ebuild seems to work as intended)

**Comment by gyakovlev** [comment]
versioned version is at the same commit as the git master right now. So you are not missing anything.
Will check it, thanks.

**Comment by stefson** [comment]
great, it's working now :)
